# Default user configuration settings
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# ==== LED ====
# Can only have one type of LED enabled. Bare or smart.
#
# Bare-LED single-color back light
# Disable by commenting out
CONFIG_ZMK_BACKLIGHT=n
#
CONFIG_ZMK_POINTING=y
# Sleep related configurations
# Milliseconds of inactivity before entering idle state (10 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support
# CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# ==== External Power ====
# Power for the display shouldn't be affected by any RGB on/off toggling.
# The D50 has a physical LED power switch to disconnect the LED if needed.
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
